set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(VIRTUAL_PREFIX ${CMAKE_CURRENT_SOURCE_DIR}/.mamba)

link_directories(${CMAKE_CURRENT_BINARY_DIR}/lib)
link_directories(${VIRTUAL_PREFIX}/Library/lib)
set(ENV{MKLROOT} ${VIRTUAL_PREFIX}/Library/lib)
